# Generated by Django 4.1.4 on 2023-03-03 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='alumni',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
