# Generated by Django 4.1.4 on 2023-03-06 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0002_alumni_created_date_alumni_is_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
