# Generated by Django 4.1.4 on 2023-03-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_activity_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
